//list const Audience _ Type
const AUDIENCE_TYPE_KH = 0;
const AUDIENCE_TYPE_NCCVN = 1;
const AUDIENCE_TYPE_NCCTQ = 2;
const AUDIENCE_TYPE_NV = 3;
const AUDIENCE_TYPE_KHAC = 4;

export {
  AUDIENCE_TYPE_KH,
  AUDIENCE_TYPE_NCCVN,
  AUDIENCE_TYPE_NCCTQ,
  AUDIENCE_TYPE_NV,
  AUDIENCE_TYPE_KHAC,
};
